/** Hardcoded demo rows from earlier seed scripts. Real seller and customer data is not in these lists. */

export const MOCK_EMAILS = [
  "customer@example.com",
  "ava@example.com",
  "seller@example.com",
  "techvault@example.com",
  "homestyle@example.com",
];

export const MOCK_STORE_SLUGS = ["prime-gear", "techvault", "homestyle"];

export const MOCK_CATEGORY_SLUGS = [
  "electronics",
  "computers",
  "phones",
  "home-kitchen",
  "fashion",
  "beauty",
  "sports",
  "books",
  "gaming",
  "accessories",
  "food",
  "apparel",
  "tech",
];

export const MOCK_PRODUCT_SLUGS = [
  "architecture-of-everyday-things",
  "aura-smart-watch-se",
  "aura-wireless-headphones",
  "aurora-55-4k-smart-tv",
  "beacon-led-strip-kit",
  "bloom-diffuser-mini",
  "bolt-65w-gan-charger",
  "brewmaster-pour-over-coffee-set",
  "cablekit-braided-usb-c-3-pack",
  "calm-night-cream",
  "chargemax-mag-wireless-pad",
  "chefedge-nonstick-pan-set-3pc",
  "chrono-minimal-watch-steel",
  "clearcase-magsafe-shell",
  "cloud-soft-tee",
  "clouddesk-usb-c-hub-8-in-1",
  "cookbook-weeknight-kitchen",
  "cove-throw-blanket",
  "daypack-slim-crossbody-bag",
  "deep-work-focus-handbook",
  "dew-glow-serum",
  "drift-wireless-mouse",
  "echo-headset-stand",
  "flex-resistance-bands",
  "flexband-resistance-set",
  "focus-flow-journal",
  "frame-14-laptop",
  "freshmist-face-mist-spray",
  "glass-screen-guard-duo",
  "glowlab-vitamin-c-serum-30ml",
  "halo-slim-wallet",
  "harbor-nonstick-pan",
  "horizon-drift-racing-wheel",
  "kitchen-confidence-cookbook",
  "lenspro-mirrorless-camera-kit",
  "loop-crossbody-bag",
  "lumen-desk-lamp",
  "nest-ceramic-mug-set",
  "nestweave-throw-blanket-queen",
  "nimbus-smart-watch",
  "nimbus-wireless-noise-canceling-headphones",
  "nova-pro-controller",
  "novaphone-x12-128gb",
  "novaphone-x12-clear-case",
  "orbit-mechanical-keyboard",
  "orbit-ultrawide-monitor-34",
  "peaktrail-hiking-daypack-25l",
  "pixelbook-pro-14-laptop",
  "pixelpad-pro-wireless-controller",
  "pivot-gaming-chair",
  "playbox-series-x-console-bundle",
  "pulse-portable-speaker",
  "pureair-compact-humidifier",
  "questrealm-vr-starter-kit",
  "quiet-usb-hub-7-port",
  "rally-running-socks-3-pack",
  "river-linen-shirt",
  "shadecraft-polarized-sunglasses",
  "silk-soft-hair-towel",
  "silktouch-moisturizing-cream",
  "soundwave-portable-bluetooth-speaker",
  "spark-key-organizer",
  "stride-everyday-sneaker",
  "stridefit-running-shorts",
  "swiftkey-mechanical-keyboard",
  "tempo-yoga-mat",
  "tiny-habits-pocket-book",
  "trail-day-pack-20l",
  "trailrunner-everyday-sneakers",
  "travellite-packable-backpack",
  "urbanlayer-merino-crew-sweater",
  "vista-webcam-1080p",
];

export function isPlaceholderImage(url: string | null | undefined) {
  if (!url) return false;
  return url.includes("picsum.photos") || url.includes("placehold.co") || url.includes("images.unsplash.com");
}
